### ISSUE TITLE
Is it possible set default image?

### ISSUE THREAD

**Issue by ricardodovalle** [chrislloyd/gravtastic#35]
I d like to change the default the default gravatar image, the G logo, is it possible?

**Comment by bmsatierf** [comment]
According to the [README](https://github.com/chrislloyd/gravtastic#complete-list-of-options):

**default:** The default avatar image none: `identicon, monsterid, wavatar or an absolute URL`.

Sample:

```ruby
current_user.gravatar_url(default: 'identicon')
```

**Comment by jbrodie** [comment]
I can't seem to get the absolute url option to work either.  Seems to continue to try to connect to i2.wp.com with the default arguments attached to the end of the request.
