### ISSUE TITLE
Is it possible to pull images from my users to gravatar app?

### ISSUE THREAD

**Issue by rodrigonunesrp** [chrislloyd/gravtastic#38]
I just want to perform save actions to user profile image into gravatar space, then it would be nice to have only 1 gem to manipulate pull and get requests to gravatar app.

**Comment by rodrigonunesrp** [comment]
I just want to perform save actions to user profile image into gravatar space, then it would be nice to have only 1 gem to manipulate pull and get requests to gravatar app.

**Comment by chrislloyd** [comment]
Hi @rodrigonunesrp. That seems like it's outside the scope of Gravtastic (which doesn't do anything with HTTP).
